### ISSUE TITLE
Getting error with below docker compose

### ISSUE THREAD

**Issue by niravjdn** [ntnj/tunwg#6]
```
version: "3.3"
services:
  tunwg:
    image: ghcr.io/ntnj/tunwg
    command: tunwg --forward=http://192.168.2.xxx:xxxx --limit=$$(htpasswd -nbB htpasswd admin admin)

```

**ERROR**

2023/07/15 14:27:35 invalid value for --limit. Use htpasswd format
